### ISSUE TITLE
[Documentation] OpenSRP server configuration checklist 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/opensrp-server-web#1014]
**OpenSRP configuration checklist**

- [ ] Set up unique Ids sources
- [ ] Set up the root location
- [ ] set up the default plan with the root location on the jurisdiction
- [ ] Create a test user.
- [ ] Create a user group (Super user)
- [ ] Create all required roles (Keycloak) -- OpenSRP web team to add all their required roles.
- [ ] Create a test team.
- [ ] Assign the user to the team
- [ ] Assign the team to a location.

These are required for both the app and the web instance
