### ISSUE TITLE
Implement server side caching for fetching OpenMRS location fetches

### ISSUE THREAD

**Issue by ndegwamartin** [OpenSRP/opensrp-server-web#464]
**Objective**
Add a cache for the API `/by-level-and-tags` on OpenSRP. Add an endpoint that forces refresh of cache when locations are modified on OpenMRS

**Implementation plan**
- [ ] Implement cache support for location fetches in the OpenSRP backend
- [ ] Implement an endpoint whose invocation clears the locations cache in the event they are updated on OpenMRS
- [ ] Update spring security rules for the end point
- [ ] Test and deploy the patch 

**NB:** This issue is related to [Server Connector Issue #40](https://github.com/OpenSRP/opensrp-server-connector/issues/40)
